#!/bin/bash
set -eu
TARGET="/var/www/mikemehl.com"
GIT_DIR="/root/mikemehl.com"
BRANCH="main"
echo "HELLO WORLD"
while read oldrev newrev ref; do
	# only checking out the master (or whatever branch you would like to deploy)
	if [ "$ref" = "refs/heads/$BRANCH" ]; then
		echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
		git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
		cd $TARGET && docker compose up --force-recreate --build --detach --wait
	else
		echo "Ref $ref received. Doing nothing. Only ${BRANCH} may be deployed on this server."
	fi
done
